#!/bin/bash

################################################
# install
# This script creates symlinks from the home directory to any desired dotfiles
# in ~/dotfiles
################################################

# Variables

readonly DIR=$(pwd)                     # dotfiles directory
readonly OLD_DIR=~/dotfiles_old         # old dotfiles backup directory
readonly FILES=$(ls | grep -ve "$(basename $0)" -e README -e pkglist)

# create dotfiles_old in HOMEDIR

echo -n "[*] Creating $OLD_DIR for backup of any existing dotfiles in ~ ..."
mkdir -p $OLD_DIR
echo "    done"

echo -n "[*] Installing pacman package list"
pacman -S - < pkglist

if [ $? -eq 0 ]; then
    echo " OK"
else
    echo " ERROR installing packages with pacman"
fi


# change to the dotfiles directory

cd $DIR

create_symlinks() {
    # move any existing dotfiles in homedir to dotfiles_old directory, then create
    # symlinks from the homedir to any files in the ~/dotfiles directory specified
    # in $files
    for file in $FILES; do
        echo "[*] Moving any existing dotfiles from ~ to $OLD_DIR"
        mv ~/.$file $OLD_DIR 2>/dev/null
        echo -n "[*] Creating symlink to $file in home directory."
        ln -s $DIR/$file ~/.$file
    done
    echo "    done"
}

main() {
    create_symlinks
    xrdb $HOME/.Xresources
}

main"$@"
