local remap = vim.keymap.set

vim.g.mapleader = " "

remap("v", "J", ":m '>+1<CR>gv=gv")
remap("v", "K", ":m '<-2<CR>gv=gv")
remap("n", "<C-d>", "<C-d>zz")
remap("n", "<C-u>", "<C-u>zz")
remap("n", "Q", "<nop>")
remap("n", "0", "^", { silent = true, noremap = true })
remap("n", "j", "gj", { silent = true, noremap = true })
remap("n", "k", "gk", { silent = true, noremap = true })
remap("n", "<TAB>", ":bnext<CR>", { silent = true, noremap = true })
remap("n", "<S-TAB>", ":bprev<CR>", { silent = true, noremap = true })
remap("i", "jk", "<ESC>", { silent = true, noremap = true })
remap("i", "kj", "<ESC>", { silent = true, noremap = true })
remap("n", "<leader>,", ":noh<CR>", { silent = true, noremap = true })
remap("n", "<C-j>", "<C-w><C-j>", { silent = true, noremap = true })
remap("n", "<C-k>", "<C-w><C-k>", { silent = true, noremap = true })
remap("n", "<C-l>", "<C-w><C-l>", { silent = true, noremap = true })
remap("n", "<C-h>", "<C-w><C-h>", { silent = true, noremap = true })
remap("n", "*", "*zz", { silent = true, noremap = true })
remap("n", "n", "nzz", { silent = true, noremap = true })
remap("n", "N", "Nzz", { silent = true, noremap = true })
remap("v", "<", "<gv", { silent = true, noremap = true })
remap("v", ">", ">gv", { silent = true, noremap = true })
remap("n", "<leader>d", ":bp<bar>sp<bar>bn<bar>bd<cr>", { silent = true, noremap = true })
remap("n", "<C-\\>", ":ToggleTerm<CR>", { silent = true, noremap = true })
remap("n", "<leader>e", ":e %:p:h/", { silent = true, noremap = true })
remap("n", "<esc>", ":noh<return><esc>", { silent = true, noremap = true })
remap("n", "<leader>s", ":%s/\\<<C-r><C-w>\\>/<C-r><C-w>/gI<Left><Left><Left>")
