local nmap = vim.api.nvim_set_keymap

vim.g.mapleader = " "

nmap("n", "0", "^", { silent = true, noremap = true })
nmap("n", "j", "gj", { silent = true, noremap = true })
nmap("n", "k", "gk", { silent = true, noremap = true })
nmap("n", "<TAB>", ":bnext<CR>", { silent = true, noremap = true })
nmap("n", "<S-TAB>", ":bprev<CR>", { silent = true, noremap = true })
nmap("i", "jk", "<ESC>", { silent = true, noremap = true })
nmap("i", "kj", "<ESC>", { silent = true, noremap = true })
nmap("n", "<leader>,", ":noh<CR>", { silent = true, noremap = true })
nmap("n", "<C-j>", "<C-w><C-j>", { silent = true, noremap = true })
nmap("n", "<C-k>", "<C-w><C-k>", { silent = true, noremap = true })
nmap("n", "<C-l>", "<C-w><C-l>", { silent = true, noremap = true })
nmap("n", "<C-h>", "<C-w><C-h>", { silent = true, noremap = true })
nmap("n", "*", "*zz", { silent = true, noremap = true })
nmap("n", "n", "nzz", { silent = true, noremap = true })
nmap("n", "N", "Nzz", { silent = true, noremap = true })
nmap("v", "<", "<gv", { silent = true, noremap = true })
nmap("v", ">", ">gv", { silent = true, noremap = true })
nmap("n", "<leader>d", ":bp<bar>sp<bar>bn<bar>bd<cr>", { silent = true, noremap = true })
nmap("n", "<C-\\>", ":ToggleTerm<CR>", { silent = true, noremap = true })
nmap("n", "<leader>e", ":e %:p:h/", { silent = true, noremap = true })
nmap("n", "<leader>f", ":Telescope find_files<cr>", { silent = true, noremap = true })
nmap("n", "<leader>g", ":Telescope live_grep<cr>", { silent = true, noremap = true })
nmap("n", "<leader>b", ":Telescope buffers<cr>", { silent = true, noremap = true })
nmap("n", "<leader>h", ":Telescope help_tags<cr>", { silent = true, noremap = true })
nmap("n", "<leader>v", ":Telescope diagnostics<cr>", { silent = true, noremap = true })
nmap("n", "<leader>xx", "<cmd>Trouble<cr>", { silent = true, noremap = true })
nmap("n", "<leader>xw", "<cmd>Trouble workspace_diagnostics<cr>", { silent = true, noremap = true })
nmap("n", "<leader>xd", "<cmd>Trouble document_diagnostics<cr>", { silent = true, noremap = true })
nmap("n", "<leader>xl", "<cmd>Trouble loclist<cr>", { silent = true, noremap = true })
nmap("n", "<leader>xq", "<cmd>Trouble quickfix<cr>", { silent = true, noremap = true })
nmap("n", "gR", "<cmd>Trouble lsp_references<cr>", { silent = true, noremap = true })
nmap("n", "<esc>", ":noh<return><esc>", { silent = true, noremap = true })
