(deftheme tao-yang
  "Created 2015-12-04.")

(custom-theme-set-variables
 'tao-yang
 '(ansi-color-names-vector ["#C2C2C2" "#161616" "#252525" "#080808" "#0E0E0E" "#161616" "#080808" "#080808"]))

(custom-theme-set-faces
 'tao-yang
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#080808" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#0E0E0E" :underline t :weight normal))))
 '(cursor ((t (:foreground "#080808" :background "#080808"))))
 '(escape-glyph ((t (:foreground "#080808" :bold t))))
 '(fringe ((t (:foreground "#E8E8E8" :background "#F0F0F0"))))
 '(header-line ((t (:inherit mode-line))))
 '(highlight ((t (:background "#F0F0F0"))))
 '(success ((t (:foreground "#252525" :weight bold))))
 '(warning ((t (:foreground "#0E0E0E" :weight bold))))
 '(compilation-info ((t (:foreground "#080808" :underline t))))
 '(compilation-line-number ((t (:foreground "#080808"))))
 '(compilation-mode-line-exit ((t (:foreground "#0E0E0E" :weight bold))))
 '(compilation-mode-line-fail ((t (:foreground "#161616" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#080808" :weight bold))))
 '(match ((t (:background "#D9D9D9" :foreground "#0E0E0E" :weight bold))))
 '(isearch ((t (:foreground "#0E0E0E" :weight bold :background "#9D9D9D"))))
 '(isearch-fail ((t (:foreground "#080808" :background "#616161"))))
 '(lazy-highlight ((t (:foreground "#0E0E0E" :weight bold :background "#C2C2C2"))))
 '(menu ((t (:foreground "#080808" :background "#F0F0F0"))))
 '(minibuffer-prompt ((t (:foreground "#080808" :color "#C2C2C2"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#E8E8E8" :background "#3C3C3C" :box nil)) (t :inverse-video t)))
 '(mode-line-inactive ((t (:foreground "#D9D9D9" :background "#9D9D9D" :box nil))))
 '(mode-line-buffer-id ((t (:foreground "#F0F0F0" :weight bold))))
 '(region ((((class color) (min-colors 89)) (:background "#252525" :foreground "#D9D9D9")) (t :inverse-video t)))
 '(secondary-selection ((t (:background "#F0F0F0"))))
 '(trailing-whitespace ((t (:background "#161616"))))
 '(vertical-border ((t (:foreground "#616161" :background "#F0F0F0"))))
 '(font-lock-builtin-face ((t (:foreground "#080808" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#616161" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#3C3C3C"))))
 '(font-lock-constant-face ((t (:foreground "#080808"))))
 '(font-lock-doc-face ((t (:foreground "#616161"))))
 '(font-lock-function-name-face ((t (:foreground "#080808"))))
 '(font-lock-keyword-face ((t (:foreground "#080808" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#080808" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#0E0E0E"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#080808" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#252525" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#3C3C3C" :slant oblique))))
 '(font-lock-type-face ((t (:foreground "#161616" :underline t))))
 '(font-lock-variable-name-face ((t (:foreground "#0E0E0E"))))
 '(font-lock-warning-face ((t (:foreground "#0E0E0E" :weight bold))))
 '(ace-jump-face-background ((t (:foreground "#9D9D9D" :background "#E8E8E8" :inverse-video nil))))
 '(ace-jump-face-foreground ((t (:foreground "#0E0E0E" :background "#C2C2C2" :inverse-video nil))))
 '(ac-candidate-face ((t (:background "#3C3C3C" :foreground "#E8E8E8" :underline nil))))
 '(ac-selection-face ((t (:background "#616161" :foreground "#080808" :underline nil))))
 '(ac-yasnippet-candidate-face ((t (:background "#3C3C3C" :foreground "#D9D9D9"))))
 '(ac-yasnippet-selection-face ((t (:background "#616161" :foreground "#080808"))))
 '(ac-gtags-candidate-face ((t (:background "#3C3C3C" :foreground "#C2C2C2"))))
 '(ac-gtags-selection-face ((t (:background "#616161" :foreground "#080808"))))
 '(popup-tip-face ((t (:background "#0E0E0E" :foreground "#E8E8E8"))))
 '(popup-scroll-bar-foreground-face ((t (:background "#9D9D9D"))))
 '(popup-scroll-bar-background-face ((t (:background "#D9D9D9"))))
 '(popup-isearch-match ((t (:background "#F0F0F0" :foreground "#080808"))))
 '(eshell-prompt ((t (:foreground "#080808" :weight bold))))
 '(eshell-ls-archive ((t (:foreground "#252525" :weight bold))))
 '(eshell-ls-backup ((t (:inherit font-lock-comment-face))))
 '(eshell-ls-clutter ((t (:inherit font-lock-comment-face))))
 '(eshell-ls-directory ((t (:foreground "#0E0E0E" :weight bold))))
 '(eshell-ls-executable ((t (:foreground "#0E0E0E" :weight bold))))
 '(eshell-ls-unreadable ((t (:foreground "#080808"))))
 '(eshell-ls-missing ((t (:inherit font-lock-warning-face))))
 '(eshell-ls-product ((t (:inherit font-lock-doc-face))))
 '(eshell-ls-special ((t (:foreground "#080808" :weight bold))))
 '(eshell-ls-symlink ((t (:foreground "#080808" :weight bold))))
 '(flycheck-error ((((supports :underline (:style wave))) (:underline (:style wave :color "#C2C2C2") :inherit unspecified)) (t (:foreground "#252525" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style wave))) (:underline (:style wave :color "#F0F0F0") :inherit unspecified)) (t (:foreground "#080808" :weight bold :underline t))))
 '(flycheck-info ((((supports :underline (:style wave))) (:underline (:style wave :color "#F0F0F0") :inherit unspecified)) (t (:foreground "#080808" :weight bold :underline t))))
 '(flycheck-fringe-error ((t (:foreground "#C2C2C2" :weight bold))))
 '(flycheck-fringe-warning ((t (:foreground "#F0F0F0" :weight bold))))
 '(flycheck-fringe-info ((t (:foreground "#F0F0F0" :weight bold))))
 '(flymake-errline ((((supports :underline (:style wave))) (:underline (:style wave :color "#161616") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#252525" :weight bold :underline t))))
 '(flymake-warnline ((((supports :underline (:style wave))) (:underline (:style wave :color "#0E0E0E") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#0E0E0E" :weight bold :underline t))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#D9D9D9")) (t :weight bold)))
 '(ido-first-match ((t (:foreground "#080808" :weight bold))))
 '(ido-only-match ((t (:foreground "#0E0E0E" :weight bold))))
 '(ido-subdir ((t (:foreground "#080808"))))
 '(ido-indicator ((t (:foreground "#080808" :background "#616161"))))
 '(linum ((t (:foreground "#0E0E0E" :background "#F0F0F0"))))
 '(org-agenda-date-today ((t (:foreground "#080808" :slant italic :weight bold))))
 '(org-agenda-structure ((t (:inherit font-lock-comment-face))))
 '(org-archived ((t (:foreground "#080808" :weight bold))))
 '(org-checkbox ((t (:background "#616161" :foreground "#080808" :box (:line-width 1 :style released-button)))))
 '(org-date ((t (:foreground "#0E0E0E" :underline t))))
 '(org-done ((t (:bold t :weight bold :foreground "#080808"))))
 '(org-formula ((t (:foreground "#0E0E0E"))))
 '(org-headline-done ((t (:foreground "#080808"))))
 '(org-hide ((t (:foreground "#D9D9D9"))))
 '(org-document-title ((t (:foreground "#080808" :height 1.9 :bold t))))
 '(org-level-1 ((t (:foreground "#080808" :height 1.5))))
 '(org-level-2 ((t (:foreground "#161616" :height 1.2))))
 '(org-level-3 ((t (:foreground "#252525" :height 1.1))))
 '(org-level-4 ((t (:foreground "#252525" :height 1.0))))
 '(org-level-5 ((t (:foreground "#252525" :height 1.0))))
 '(org-level-6 ((t (:foreground "#252525" :height 1.0))))
 '(org-level-7 ((t (:foreground "#252525" :height 1.0))))
 '(org-level-8 ((t (:foreground "#3C3C3C" :height 1.0))))
 '(org-link ((t (:foreground "#0E0E0E" :underline t))))
 '(org-scheduled ((t (:foreground "#080808"))))
 '(org-scheduled-previously ((t (:foreground "#161616"))))
 '(org-scheduled-today ((t (:foreground "#0E0E0E"))))
 '(org-sexp-date ((t (:foreground "#0E0E0E" :underline t))))
 '(org-special-keyword ((t (:inherit font-lock-comment-face))))
 '(org-table ((t (:foreground "#0E0E0E"))))
 '(org-tag ((t (:bold t :weight bold))))
 '(org-time-grid ((t (:foreground "#0E0E0E"))))
 '(org-todo ((t (:bold t :foreground "#161616" :weight bold))))
 '(org-upcoming-deadline ((t (:inherit font-lock-keyword-face))))
 '(org-warning ((t (:bold t :foreground "#161616" :weight bold :underline nil))))
 '(org-column ((t (:background "#D9D9D9"))))
 '(org-column-title ((t (:background "#D9D9D9" :underline t :weight bold))))
 '(org-mode-line-clock ((t (:foreground "#080808" :background "#D9D9D9"))))
 '(org-mode-line-clock-overrun ((t (:foreground "#C2C2C2" :background "#252525"))))
 '(org-ellipsis ((t (:foreground "#080808" :underline t))))
 '(org-footnote ((t (:foreground "#080808" :underline t))))
 '(org-meta-line ((t (:foreground "#3C3C3C" :height 0.5))))
 '(org-block-background ((t (:background "#F0F0F0" :height 1))))
 '(outline-1 ((t (:foreground "#0E0E0E"))))
 '(outline-2 ((t (:foreground "#080808"))))
 '(outline-3 ((t (:foreground "#161616"))))
 '(outline-4 ((t (:foreground "#0E0E0E"))))
 '(outline-5 ((t (:foreground "#080808"))))
 '(outline-6 ((t (:foreground "#0E0E0E"))))
 '(outline-7 ((t (:foreground "#616161"))))
 '(outline-8 ((t (:foreground "#616161"))))
 '(show-paren-mismatch ((t (:foreground "#C2C2C2" :background "#616161" :weight bold))))
 '(show-paren-match ((t (:foreground "#0E0E0E" :background "#D9D9D9" :weight bold))))
 '(term-color-black ((t (:foreground "#C2C2C2" :background "#D9D9D9"))))
 '(term-color-red ((t (:foreground "#252525" :background "#616161"))))
 '(term-color-green ((t (:foreground "#252525" :background "#0E0E0E"))))
 '(term-color-yellow ((t (:foreground "#0E0E0E" :background "#080808"))))
 '(term-color-blue ((t (:foreground "#161616" :background "#616161"))))
 '(term-color-magenta ((t (:foreground "#161616" :background "#161616"))))
 '(term-color-cyan ((t (:foreground "#080808" :background "#0E0E0E"))))
 '(term-color-white ((t (:foreground "#080808" :background "#616161"))))
 '(undo-tree-visualizer-active-branch-face ((t (:foreground "#080808" :weight bold))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#252525" :weight bold))))
 '(undo-tree-visualizer-default-face ((t (:foreground "#080808"))))
 '(undo-tree-visualizer-register-face ((t (:foreground "#080808"))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "#080808"))))
 '(web-mode-builtin-face ((t (:inherit font-lock-builtin-face))))
 '(web-mode-comment-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-constant-face ((t (:inherit font-lock-constant-face))))
 '(web-mode-css-at-rule-face ((t (:foreground "#0E0E0E"))))
 '(web-mode-css-pseudo-class-face ((t (:foreground "#080808" :weight bold))))
 '(web-mode-doctype-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-folded-face ((t (:underline t))))
 '(web-mode-function-name-face ((t (:foreground "#0E0E0E"))))
 '(web-mode-html-attr-name-face ((t (:foreground "#0E0E0E"))))
 '(web-mode-html-attr-value-face ((t (:inherit font-lock-string-face))))
 '(web-mode-html-tag-face ((t (:foreground "#080808"))))
 '(web-mode-keyword-face ((t (:inherit font-lock-keyword-face))))
 '(web-mode-preprocessor-face ((t (:inherit font-lock-preprocessor-face))))
 '(web-mode-string-face ((t (:inherit font-lock-string-face))))
 '(web-mode-type-face ((t (:inherit font-lock-type-face))))
 '(web-mode-variable-name-face ((t (:inherit font-lock-variable-name-face))))
 '(web-mode-symbol-face ((t (:inherit font-lock-constant-face))))
 '(web-mode-warning-face ((t (:inherit font-lock-warning-face))))
 '(whitespace-space ((t (:background "#9D9D9D" :foreground "#9D9D9D"))))
 '(whitespace-hspace ((t (:background "#9D9D9D" :foreground "#9D9D9D"))))
 '(whitespace-tab ((t (:background "#252525"))))
 '(whitespace-newline ((t (:foreground "#9D9D9D"))))
 '(whitespace-trailing ((t (:background "#161616"))))
 '(whitespace-line ((t (:background "#F0F0F0" :foreground "#161616"))))
 '(whitespace-space-before-tab ((t (:background "#0E0E0E" :foreground "#0E0E0E"))))
 '(whitespace-indentation ((t (:background "#080808" :foreground "#161616"))))
 '(whitespace-empty ((t (:background "#080808"))))
 '(whitespace-space-after-tab ((t (:background "#080808" :foreground "#161616"))))
 '(markdown-header-delimiter-face ((t (:inherit font-lock-function-name-face :weight bold :foreground "#C2C2C2"))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face :height 1.5))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face :height 1.3))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face :underline t :height 1.2))))
 '(markdown-header-face-4 ((t (:inherit markdown-header-face :underline t :height 1.1))))
 '(markdown-header-face-5 ((t (:inherit markdown-header-face :underline t))))
 '(markdown-header-face-6 ((t (:inherit markdown-header-face :underline t))))
 '(markdown-link-face ((t (:underline t :foreground "#080808"))))
 '(markdown-url-face ((t (:underline t :foreground "#080808"))))
 '(default ((t (:foreground "#252525" :background "#F0F0F0")))))

(provide-theme 'tao-yang)
